SellFlowWeb/Controllers/AnuncioController.cs
using ApiClient.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Models;
using SellFlowWeb.Models.ApiRequest;
using SellFlowWeb.Models.DataView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SellFlowWeb.Controllers
{
    public class AnuncioController : BaseController
    {
        private readonly IAnuncioClient _anuncioClient;
        private readonly IProdutoClient _produtoClient;

        public AnuncioController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _anuncioClient = serviceProvider.GetService<IAnuncioClient>();
            _produtoClient = serviceProvider.GetService<IProdutoClient>();
        }

        public async Task<IActionResult> Index(int usuario)
        {
            var _ret = await _anuncioClient.GetAll(usuario);
            var _anuncios = new Mapper(AutoMapperConfig.RegisterMappings()).Map<List<AnuncioDataView>>(_ret.dados);
            return SessionExists(View(_anuncios));
        }

        [Route("{controller}/Visualizar/{id}")]
        public async Task<IActionResult> Visualizar(long id)
        {
            var _ret = await _anuncioClient.Get(id);
            var anucio = new Mapper(AutoMapperConfig.RegisterMappings()).Map<AnuncioDataView>(_ret.dados.FirstOrDefault());

            return View(anucio);
        }

        public IActionResult Criar()
        {
            @ViewBag.message = TempData["message"];
            @ViewBag.produtos = new Mapper(AutoMapperConfig.RegisterMappings()).Map<List<ProdutoDisplayDataView>>(
                                            _produtoClient.GetAll(HttpContext.Session.GetInt32("idusuario").Value).GetAwaiter().GetResult().dados);
            return SessionExists(View());
        }

        [Route("{controller}/Editar/{usuario}/{id}")]
        public async Task<IActionResult> Editar(long usuario, long id)
        {
            @ViewBag.message = TempData["message"];
            @ViewBag.produtos = new Mapper(AutoMapperConfig.RegisterMappings()).Map<List<ProdutoDisplayDataView>>(
                                            _produtoClient.GetAll(HttpContext.Session.GetInt32("idusuario").Value).GetAwaiter().GetResult().dados);
            var ret = await _anuncioClient.Get(id, usuario);
            var _anuncios = new Mapper(AutoMapperConfig.RegisterMappings()).Map<IEnumerable<AnuncioDataView>>(ret.dados);
            return SessionExists(View(_anuncios.FirstOrDefault()));
        }

        public async Task<IActionResult> Salvar(AnuncioDataView obj)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                var _mapper = new Mapper(AutoMapperConfig.RegisterMappings());
                var _produto = _mapper.Map<AnuncioApiRequest>(obj);
                var idusuario = HttpContext.Session.GetInt32("idusuario").Value;
                ReturnModel<AnuncioModel> _ret = new();
                _ret = await _anuncioClient.Save(_produto);

                if (!_ret.status)
                {
                    TempData["message"] = "Não foi possível Salvar!";
                    if (obj.id.HasValue && obj.id > 0)
                    {
                        return View("Editar", new { id = obj.id, usuario = idusuario });
                    }
                    else
                    {
                        return View("Criar");
                    }
                }
                return RedirectToAction("Index", new { usuario = idusuario });
            }
            return redirect;
        }

        public async Task<IActionResult> ExcluirAsync(long id)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                ReturnModel<AnuncioModel> _ret = await _anuncioClient.Delete(id);

                if (!_ret.status)
                {
                    TempData["message"] = "Não foi possível Excluir!";
                    return RedirectToAction("Index", new { usuario = HttpContext.Session.GetInt32("idusuario").Value });
                }

                return RedirectToAction("Index", new { usuario = HttpContext.Session.GetInt32("idusuario").Value });
            }
            return redirect;
        }
    }
}

SellFlowWeb/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ApiClient.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using SellFlowWeb.Models.ApiRequest;

namespace SellFlowWeb.Controllers
{
    public class LoginController : BaseController
    {
        private readonly IPessoaClient _pessoaClient;
        public LoginController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _pessoaClient = serviceProvider.GetService<IPessoaClient>();
        }

        public IActionResult Index()
        {
            HttpContext.Session.Clear();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [HttpPost("[controller]/Auth")]
        public async Task<IActionResult> Auth([FromBody]ApiRequestAuth obj)
        {
            if (obj.id > 0 && !string.IsNullOrWhiteSpace(obj.token))
            {
                var _ret = await _pessoaClient.GetPessoaByUsuario(obj.id);
                if (_ret != null && _ret.status && _ret.dados.Count > 0)
                {
                    var _pessoa = _ret.dados.FirstOrDefault();
                    HttpContext.Session.SetInt32("idusuario", (int)_pessoa.usuarioObj.id);
                    HttpContext.Session.SetInt32("idpermissao", (int)(_pessoa.usuarioObj.permissao.HasValue ? _pessoa.usuarioObj.permissao : 2));
                    HttpContext.Session.SetString("email", _pessoa.usuarioObj.email);
                    HttpContext.Session.SetString("nome", _pessoa.nome);
                    HttpContext.Session.SetString("sobrenome", _pessoa.sobrenome);
                    HttpContext.Session.SetString("cpf", _pessoa.cpf);
                    HttpContext.Session.SetString("token", obj.token);
                    return Ok(true);
                } 
            }
            TempData["message"] = "Não foi possível realizar o login.";
            return View("Index");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return View("Index");
        }

    }
}

SellFlowWeb/Controllers/PaginaController.cs
using Models;
using System;
using AutoMapper;
using System.Linq;
using ApiClient.Interfaces;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using SellFlowWeb.Models.DataView;
using SellFlowWeb.Models.ApiRequest;
using Microsoft.Extensions.DependencyInjection;

namespace SellFlowWeb.Controllers
{
    public class PaginaController : BaseController
    {
        private readonly IPaginaClient _paginaClient;
        private readonly IPermissaoClient _permissaoClient;

        public PaginaController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _paginaClient = serviceProvider.GetService<IPaginaClient>();
            _permissaoClient = serviceProvider.GetService<IPermissaoClient>();
        }

        public async Task<IActionResult> Index()
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                var returnModel = await _paginaClient.GetAll();
                var _pagina = new Mapper(AutoMapperConfig.RegisterMappings()).Map<List<PaginaDataView>>(returnModel?.dados);
                return View(_pagina.OrderBy(x => x.caminho).ThenBy(x => x.nome));
            }
            return redirect;
        }

        public async Task<IActionResult> Criar()
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                @ViewBag.permissoes = (await _permissaoClient.GetAll())?.dados;
                @ViewBag.message = TempData["message"];
                return SessionExists(View());
            }
            return redirect;
        }

        public async Task<IActionResult> Editar(long id)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                @ViewBag.permissoes = (await _permissaoClient.GetAll())?.dados;
                @ViewBag.message = TempData["message"];
                var ret = await _paginaClient.Get(id);
                var _pagina = new Mapper(AutoMapperConfig.RegisterMappings()).Map<IEnumerable<PaginaDataView>>(ret.dados);
                return SessionExists(View(_pagina.FirstOrDefault()));
            }
            return redirect;
        }

        public async Task<IActionResult> Salvar(PaginaDataView obj)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                var _mapper = new Mapper(AutoMapperConfig.RegisterMappings());
                var _produto = _mapper.Map<PaginaApiRequest>(obj);

                ReturnModel<PaginaModel> _ret = new();
                _ret = await _paginaClient.Save(_produto);

                if (!_ret.status)
                {
                    TempData["message"] = "Não foi possível Salvar!";
                    if (obj.id > 0)
                    {
                        return View("Editar", new { id = obj.id });
                    }
                    else
                    {
                        return View("Criar");
                    }
                }
         
                return RedirectToAction("Index");
            }
            return redirect;
        }

        public async Task<IActionResult> ExcluirAsync(long id)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                ReturnModel<PaginaModel> _ret = await _paginaClient.Delete(id);

                if (!_ret.status)
                {
                    TempData["message"] = "Não foi possível Excluir!";
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            return redirect;
        }
    }
}

SellFlowWeb/Controllers/ProdutoController.cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ApiClient.Interfaces;
using System;
using Models;
using System.Linq;
using SellFlowWeb.Models.ApiRequest;
using SellFlowWeb.Models.DataView;
using AutoMapper;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace SellFlowWeb.Controllers
{
    public class ProdutoController : BaseController
    {
        private readonly IProdutoClient _produtoClient;

        public ProdutoController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _produtoClient = serviceProvider.GetService<IProdutoClient>();
        }

        public async Task<IActionResult> Index(int usuario)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                var _ret = await _produtoClient.GetAll(usuario);
                var _produtos = new Mapper(AutoMapperConfig.RegisterMappings()).Map<List<ProdutoDisplayDataView>>(_ret.dados);
                return View(_produtos);
            }
            return redirect;
        }

        public IActionResult Criar()
        {
            @ViewBag.message = TempData["message"];
            return SessionExists(View());
        }

        [Route("{controller}/Editar/{usuario}/{id}")]
        public async Task<IActionResult> Editar(long usuario, long id)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                @ViewBag.message = TempData["message"];
                var ret = await _produtoClient.Get(id, usuario);
                var _produtos = new Mapper(AutoMapperConfig.RegisterMappings()).Map<IEnumerable<ProdutoDataView>>(ret.dados);
                return View(_produtos.FirstOrDefault());
            }
            return redirect;
        }

        public async Task<IActionResult> Salvar(ProdutoDataView obj)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                var _mapper = new Mapper(AutoMapperConfig.RegisterMappings());
                var _produto = _mapper.Map<ProdutoApiRequest>(obj);
                var idusuario = HttpContext.Session.GetInt32("idusuario").Value;
                ReturnModel<ProdutoModel> _ret = new();
                _ret = await _produtoClient.Save(_mapper.Map<ProdutoModel>(_produto));

                if (!_ret.status)
                {
                    TempData["message"] = "Não foi possível Salvar!";
                    if(obj.id > 0)
                    {
                        return View("Editar", new { id = obj.id, usuario = idusuario});
                    }
                    else
                    {
                        return View("Criar");
                    }

                }

                return RedirectToAction("Index", new { usuario = idusuario });

            }
            return redirect;
        }

        public async Task<IActionResult> ExcluirAsync(long id)
        {
            var redirect = SessionExists();
            if (redirect is null)
            {
                ReturnModel<ProdutoModel> _ret = await _produtoClient.Delete(id);

                if(!_ret.status)
                {
                    TempData["message"] = "Não foi possível Excluir!";
                    return RedirectToAction("Index", new { usuario = HttpContext.Session.GetInt32("idusuario").Value });
                }

                return RedirectToAction("Index", new { usuario = HttpContext.Session.GetInt32("idusuario").Value });
            }
            return redirect;
        }

    }
}

SellFlowWeb/Views/Shared/AcessoNegado.cshtml
@model Models.ErrorViewModel
@{
    ViewData["Title"] = "Acesso Negado";
    Layout = "~/Views/Shared/_Imports.cshtml";
}

<header class="m-3">
    <div class="container justify-content-center">
        <div class="row justify-content-center">
            <div class="col-2">
                <h1>SellFlow</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-3">
                <h2 class="text-danger">Acesso Negado</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="text-center">
                <p class="text-danger mb-1">Você não possui permissões suficientes para acessar essa página.</p>
                <p class="text-danger">Volte a tela inicial ou realize o login com outras credenciais.</p>
            </div>
        </div>
    </div>
</header>
<div class="container my-5">

    <div class="row row-cols-auto justify-content-center">
        <div class="col">
            <a asp-action="Index" asp-controller="Home" class="btn btn-lg btn-primary">Voltar Tela Incial</a>
        </div>

        <div class="col">
            <a asp-action="Index" asp-controller="Login" class="btn btn-lg btn-outline-info"><i class="bi bi-box-arrow-in-right mx-1"></i>Realizar Login</a>
        </div>

    </div>
</div>

SellFlowWeb/Views/Shared/_AnuncioCard.cshtml
@using Models
@model SellFlowWeb.Models.DataView.AnuncioDataView


<div class="col">
    <div class="card h-100">
        @{ 
            <img src="@Model.produtoObj.imagemdestaque" class="card-img-top imgCard" alt="...">
        }
        @if (double.Parse(Model.percentPromocao.Replace("%", "")) > 0)
        {
            <span class="badge rounded-pill bg-success mx-2">Desconto @Model.percentPromocao</span>
        }
        <div class="card-body">
            <h4 class="card-title">@Model.nome</h4>
            @if (double.Parse(Model.percentPromocao.Replace("%", "")) > 0)
            {
                <h5 class="card-text text-success">R$ @Model.valorDecimal - <s class="text-secondary">R$ @Model.produtoObj.valorDecimal</s></h5>
            }
            else
            {
                <h5 class="card-text">R$ @Model.valorDecimal</h5>
            }
            <h6 class="card-text">@Model.produtoObj.nome</h6>
            <p class="card-text">Vendedor - @Model.vendedor</p>
            @Html.ActionLink("Visualizar", "Visualizar", "Anuncio", new { id = Model.id}, new { @class = "btn btn-primary" })
        </div>
        <div class="card-footer">
            @if ((DateTime.Now.Date - Model.dataCriacao.Date).TotalDays > 0)
            {
                var totaldays = (DateTime.Now.Date - Model.dataCriacao.Date).TotalDays;
                <small class="text-muted">Postado a @totaldays dias.</small>
            }
            else
            {
                var totalminutes = ((int)(DateTime.Now - Model.dataCriacao).TotalMinutes);
                <small class="text-muted">Postado a @totalminutes minutos.</small>
            }
        </div>
    </div>
</div>

SellFlowWeb/Views/Shared/_Imports.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellFlowWeb</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    @RenderBody()
    <footer class="border-top text-muted">
        <div class="container p-3">
            &copy; 2021 - SellFlowWeb - <a href="https://github.com/FelipeJSousa">Felipe Sousa</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css">
    @await RenderSectionAsync("MainScripts", required: false)
</body>
</html>

SellFlowWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    Layout = "~/Views/Shared/_Imports.cshtml";
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SellFlowWeb</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 nav justify-content-center">
                    @if (Context.Request.HttpContext.Session.GetInt32("idpermissao").HasValue && Context.Request.HttpContext.Session.GetInt32("idpermissao").Value != 2)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Tela Inicial</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Anuncios", "Index", "Anuncio", new { usuario = Context.Request.HttpContext.Session.GetInt32("idusuario").Value }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Produtos", "Index", "Produto", new { usuario = Context.Request.HttpContext.Session.GetInt32("idusuario").Value }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pagina" asp-action="Index">Paginas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Permissao" asp-action="Index">Permissões</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                    }
                </ul>
                @if (Context.Request.HttpContext.Session.GetInt32("idpermissao").HasValue && Context.Request.HttpContext.Session.GetInt32("idpermissao").Value == 2)
                {
                    <a asp-action="Index" asp-controller="Login" class="btn btn-outline-light nav-link"><i class="bi bi-box-arrow-in-right mx-1"></i>Realizar Login</a>
                }
                else
                {
                    <a asp-action="Perfil" asp-controller="Usuario" class="btn btn-outline-light nav-link"><i class="bi bi-person"></i> @HttpContextAccessor.HttpContext.Session.GetString("email")</a>
                    <a asp-action="Logout" asp-controller="Login" class="btn btn-outline-secondary"><i class="bi bi-box-arrow-left"></i> Sair</a>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@section MainScripts{ 

    @await RenderSectionAsync("Scripts", required: false)
}

SellFlowWeb/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellFlowWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="mb-3">
        <div class="container justify-content-center">
            <div class="row justify-content-center">
                <div class="col-2">
                    <h1>SellFlow</h1>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-3">
                    <h3>Anuncios Diversos</h3>
                </div>
            </div>    
        </div>
    </header>
    <div class="container border-1 shadow">
        <main role="main" class="py-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SellFlowWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css">
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>